export default {
  vscodeLogo: require("@/assets/images/vscode.png"),
  css: require("@/assets/images/css.png"),
  js: require("@/assets/images/js.png"),
  json: require("@/assets/images/json.png"),
  markdown: require("@/assets/images/markdown.png"),
  jsx: require("@/assets/images/react.png"),
  tsx: require("@/assets/images/reactts.png"),
  typescript: require("@/assets/images/typescript.png"),
  feastly: require("@/assets/images/feastly.png"),
  spotify: require("@/assets/images/spotify.png"),
  portfolio: require("@/assets/images/portfolio.png"),
  recipehunt: require("@/assets/images/recipehunt.png"),
  stepinstyle: require("@/assets/images/stepinstyle.png"),
};
